version: 1.0

model:
  name: "UNet++"
  in_channels: 4
  encoder_depth: 5
  encoder: "efficientnet-b4"

data_dirs:
  root: 'C:\Users\LARHOD\Documents\GIS\MapAI-Competition\data\overlapping_data'
  train: 'train'
  validation: 'validation'
  images: "images"
  lidar: "lidar"
  masks: "masks"

num_classes: 2
classes: ["background", "building"]
class_to_color:
  "background": 0
  "building": 1

augmentation: 'normal'  # None, 'normal', 'hard', 'very_hard'
lidar_augs: 'normal' # None, 'normal'

training:
  losses:
    names: ['DiceLoss']
    weights: [1.0]
    DiceLoss:
      init_params:
        mode: "multiclass"

  metrics:
    mask:
      - name: MicroIoU
        init_params:

  optimizer:
    name: Adam
    lr: 0.0001

  scheduler:
    name: PolyLR
    init_params:
      epochs: 50

  # fit:
  #   epochs: 50
  #   accumulation_steps: 4

imagesize: 512

train:
  epochs: 50
  batchsize: 2
  shuffle: True
  num_workers: 0
  data_ratio: 0.1

validation:
  batchsize: 2
  shuffle: True
  num_workers: 0
  data_ratio: 1.0