version: 1.0

num_classes: 2
classes: ["background", "building"]
class_to_color:
  "background": 0
  "building": 1

model:
  name: "UNet++"
  in_channels: 3
  encoder_depth: 5

data_dirs:
  root: 'C:\Users\LARHOD\Documents\GIS\MapAI-Competition\data\overlapping_data'
  images: "images"
  lidar: "lidar"
  masks: "masks"

training:
  losses:
    names: [DiceLoss]
    weighting: [1.0]
    DiceLoss:
      init_params:

  metrics:
    mask:
      - name: MicroIoU
        init_params:

  optimizer:
    name: Adam
    lr: 0.0001

  scheduler:
    name: PolyLR
    init_params:
      epochs: 50

  # fit:
  #   epochs: 50
  #   accumulation_steps: 4

imagesize: 512

train:
  epochs: 50
  batchsize: 8
  shuffle: True
validation:
  batchsize: 1
  shuffle: False
task1:
  batchsize: 1
  shuffle: False
task2:
  batchsize: 1
  shuffle: False