version: 1.0

model:
  name: "UNet"
  encoder_depth: 5
  encoder: "efficientnet-b4"
  aux_head: False
  aux_head_params:
    classes: 1 # binary building / no building classification
    pooling: "avg" # "max",  "avg"
    dropout: 0.2 # default 0.0


dataset: 'landcover' # mapai, mapai_reclassified, mapai_lidar_masks, landcover


augmentation:
  initial: 'normal'  # None, 'normal', 'hard', 'very_hard'
  warmup_epochs: 3 # number of epochs before switching to augmentation cycle
  cycle: ["hard", "normal", "normal"] # select augmentations with index (epoch - warmup_epochs) % len(cycle)

lidar_augs:
  clip_min: -1.0
  clip_max: 30.0
  norm: "max" # "max", "min_max"
  norm_basis: "clip" # "clip", "image"

imagesize: 512
training:
  losses:
    # "DiceLoss": smp.losses.DiceLoss,
    # "JaccardLoss": smp.losses.JaccardLoss,
    # "TverskyLoss": smp.losses.TverskyLoss,
    # "FocalLoss": smp.losses.FocalLoss,
    # "LovaszLoss": smp.losses.LovaszLoss,
    # "CrossEntropy": smp.losses.SoftBCEWithLogitsLoss, OR smp.losses.SoftCrossEntropyLoss if num_classes > 1
    names: ['CrossEntropy']
    weights: [1.0]
    CrossEntropy:
      init_params:
        smooth_factor: 0.01

  optimizer:
    name: RAdam # Adam, SGD, RAdam, AdamWarmup
    init_params:
      lr: 0.0001

  scheduler:
    name: MultiStep # PolyLR, MultiStep
    init_params:
      milestones: [3]
  # fit:
  #   epochs: 50
  #   accumulation_steps: 4


testing:
  interpolation: bilinear # bicubic, bilinear
  antialias: True
  erode_val_preds: True

train:
  epochs: 1
  batchsize: 2
  shuffle: True
  num_workers: 2
  data_ratio: 0.0001

validation:
  batchsize: 2
  shuffle: False
  num_workers: 0
  data_ratio: 0.01