
data_dirs:
  root: './data/mapai'
  train: 'train'
  validation: 'validation'
  images: "images"
  lidar: "lidar"
  # masks_train: "masks"
  masks: "masks"


num_classes: 1
classes: ["background", "building"]
class_to_color:
  "background": 0
  "building": 1